<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup Label="Library">
    <PackageVersion Include="MahApps.Metro" Version="3.0.0-rc0529" />
    <PackageVersion Include="Microsoft.Windows.CsWin32" Version="0.3.162" />
    <PackageVersion Include="System.Memory" Version="4.6.3" />
    <PackageVersion Include="System.ValueTuple" Version="4.6.2" />
  </ItemGroup>
  <ItemGroup Label="Additional">
    <PackageVersion Include="MahApps.Metro.IconPacks.Modern" Version="6.2.1" />
    <PackageVersion Include="JetBrains.Annotations" Version="2026.2.0" />
    <PackageVersion Include="WpfAnalyzers" Version="4.1.1" />
  </ItemGroup>
</Project>